#define OCAML_VERSION_MAJOR 4
#define OCAML_VERSION_MINOR 6
#define OCAML_VERSION_PATCHLEVEL 1
#define OCAML_VERSION_ADDITIONAL "BS"
#define OCAML_VERSION 40601
#define OCAML_VERSION_STRING "4.06.1+BS"
